# Generated by Django 5.1.6 on 2025-02-12 10:03

from django.utils import timezone
import django.db.models.deletion
from django.db import migrations, models
def create_sample_ride_locations(apps, schema_editor):
    Ride = apps.get_model('rideApp', 'Ride')
    RideLocation = apps.get_model('rideApp', 'Ride_Location')
    
    # Create sample ride locations for testing
    test_ride = Ride.objects.first()  # Get the first ride or create one
    
    sample_locations = [
        {
            'latitude': 12.9716,
            'longitude': 77.5946,
            'location_name': 'Starting Point',
            'destination_latitude': 13.0827,
            'destination_longitude': 77.6899,
            'current_time': timezone.now()
            
        }
    
    ]
    
    for location_data in sample_locations:
        RideLocation.objects.create(
            ride=test_ride,
            **location_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rideApp', '0003_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(max_length=255)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='rideApp.ride')),
            ],
        ),
        migrations.RunPython(create_sample_ride_locations)
    ]
