# Generated by Django 5.1.6 on 2025-02-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.contrib.auth.models import User

def seed_drivers(apps, schema_editor):
    AvailableDriver = apps.get_model('rideApp', 'AvailableDriver')
    User = apps.get_model('auth', 'User')
    
    # Create test drivers with different timestamps
    driver_data = [
        {
            'driver_id': 3,
            'latitude': 13.0098,
            'longitude': 77.5551,
            'last_ride_time': timezone.now() - timezone.timedelta(hours=2)
        },
        {
            'driver_id': 4,
            'latitude': 12.9952,
            'longitude': 77.5847,
            'last_ride_time': timezone.now() - timezone.timedelta(minutes=45)
        },
        {
            'driver_id': 5,
            'latitude': 13.0227,
            'longitude': 77.6675,
            'last_ride_time': timezone.now() - timezone.timedelta(hours=1)
        },
        {
            'driver_id': 6,
            'latitude': 12.9352,
            'longitude': 77.6245,
            'last_ride_time': timezone.now() - timezone.timedelta(minutes=30)
        }
    ]

    for data in driver_data:
        user = User.objects.get(id=data['driver_id'])
        AvailableDriver.objects.create(
            driver=user,
            current_latitude=data['latitude'],
            current_longitude=data['longitude'],
            status='available',
            last_ride_completed_time=data['last_ride_time']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rideApp', '0004_ride_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_ride_completed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
         migrations.RunPython(seed_drivers),
    ]
